cameras:
    - name: Infrared
      port: 5-1
      capabilities: video/x-raw,width=320,height=240,framerate=30/1
      v4l2settings: -c auto_gain=0 -c main_gain=0
      v4l2settings-off: -c auto_gain=1
      processor: /home/odroid/getting2rectanglesandcomparing.py
      record: No
      bitrate: 256kbps

    - name: DriveCam
      port: 1-3-1
      record: No
      capabilities: image/jpeg,width=800,height=448,framerate=30/1
      bitrate: 1500kbps