cameras:
    - name: DriveCam
      port: 2-1-1
      record: Yes
      capabilities: video/x-h264,width=1280,height=720,framerate=30/1
    - name: SelfieCam
      port: 2-1-2
      record: Yes
      capabilities: video/x-h264,width=1280,height=720,framerate=30/1